modLoader="javafml"
loaderVersion="[36,)"
license="CBT license"

[[mods]]
modId="complicatedplanes"
displayName="Complicated Planes"
logoFile="complicatedplanes_icon.png"


authors="igorstan"

description='''
    Finally: Complicated Planes
'''
[[dependencies.complicatedplanes]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.complicatedplanes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
